name: example
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  xml: ^4.1.0

dev_dependencies:
  test: ^1.14.3
  servirtium:
    path: ../