name: servirtium
description: Service Virtualization standard using Markdown for recorded and played back HTTP conversations.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  isolate: 2.0.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.12.0
