name: servirtium
description: Service Virtualization standard using Markdown for recorded and played back HTTP conversations.
version: 0.0.1
homepage: https://servirtium.dev

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  isolate: ^2.0.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.3